### ISSUE TITLE
va-summary-box throws error when a headline slot is not used in component

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/vets-design-system-documentation#2557]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

We are using this component without a headline in the Profile, and it is throwing an error. It doesn't break rendering or anything like that, so isn't a critical bug, but figured I would report it.

When just passing content in without a headline slot, we will get this error in the console:

```
console.js:213 TypeError: Cannot read properties of undefined (reading 'textContent')
    at a.componentWillLoad (va-summary-box.entry.js:1:10421)
    at safeCall (index-5ed038a1.js:1:16988)
    at dispatchHooks (index-5ed038a1.js:1:15277)
    at Array.r (index-5ed038a1.js:1:14957)
    at consume (index-5ed038a1.js:2:1101)
    at flush (index-5ed038a1.js:2:1208) undefined
```
Looks like the issue originates from this line: [https://github.com/department-of-veterans-affairs/component-library/blob/main/pack[…]web-components/src/components/va-summary-box/va-summary-box.tsx](https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-summary-box/va-summary-box.tsx#L29)

So hopefully should be pretty easy to patch. Thanks!

## What I expected to happen

Summary box not throwing error in console

## Reproducing
- Formation version:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

Steps to reproduce:

1. Create instance of summary-box with no headline slot
2. Open console to see error
3. Profit?

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/2557?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by adamwhitlock1** [comment]
![Screenshot 2024-03-07 at 11 29 34 AM](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/8332986/27bbb6ac-d22a-4abc-a9a0-f045394f12a6)

We are currently using it in our Direct Deposit page without a title.

**Comment by humancompanion-usds** [comment]
Summary box (aka Featured content) was not intended for this purpose. You can point your designer to the guidance: https://design.va.gov/components/summary-box

This also doesn't seem to warrant an Alert. Thus I would recommend that this is either plain content or something new. The Claim Status Tool folks are also working on a solution to this gap we have.

**Comment by andaleliz** [comment]
@humancompanion-usds we reviewed this a design system council meeting, and the feedback I got on the content was only that it needed a heading. We are planning to add the heading with the next round of design updates (coming in a few sprints). IMO, fraud information is critical information on the direct deposit page, and having it in the summary box helps draw the appropriate attention (I agree with you that it wouldn't warrant an alert).  The heading especially will ensure screenreader users who navigate by heading won't miss it.

**Comment by andaleliz** [comment]
Actually wait - I'm totally wrong about reviewing this in a design system council meeting. I'm confusing this with a different component that we had questions about at the same time.  Either way, it still feels like this type of information does fit into the guidance on the component page:
- it has key details that readers shouldn’t miss. 
- The content should be “evergreen”, not time sensitive.

[This mock-up](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=276-13270&mode=design&t=6M8I44uxbxNxvSyh-11) shows where we are headed with this content, if that helps. Then, once a resources and support page is created with fraud info, we'll link to that instead of host it on our page.

**Comment by humancompanion-usds** [comment]
@andaleliz - Understood. I was mostly responding to the version as presented here. I think if a message starts with "Note:" then it is either plain content or another component but doesn't warrant the Summary box. We have been pretty loose with enforcing the intent of the Summary box. Adding a header is perfectly fine given that you all were already using this component. However, we're not going to alter the web-component to allow for Summary box without a header. In fact, I'm going to update this issue to reflect that we should enforce that a header be used in future.

**Comment by andaleliz** [comment]
@humancompanion-usds thank you! I think that makes a ton of sense, especially after seeing multiple screenreader users navigate by heading in my last study.  

@adamwhitlock1 would it be possible to go ahead and add the CAIA-approved heading to the summary box, and update the content? 

heading: What to do if you think you’ve been the victim of bank fraud

content: Call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. 


[Here's a mock-up ](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=276-13270&mode=design&t=6M8I44uxbxNxvSyh-11) that shows this in action. I wouldn't worry about reordering it on the page at this point, that feels out of scope for this task.

**Comment by adamwhitlock1** [comment]
Sounds like a good plan forward! 

I'll add the heading to the summary box asap. Thanks @andaleliz and @humancompanion-usds for the guidance and clarification.
